### ISSUE TITLE
Missing checks on randomness used in the sign function in schnorr.rb

### ISSUE THREAD

**Issue by AmritKumar** [FireStack-Lab/LaksaRuby#2]
**PROBLEM:** The sign function uses a random `k_bn`. In the current implementation, `k_bn` is generated as a set of 32 random bytes. However, Schnorr signing requires `k_bn` to be smaller than `N` (order of the elliptic group) which in turn is smaller than the largest value represented by a set of 32 random random bytes.

**SOLUTION:** Instead of generating a set of 32 random bytes, we should instead generate a random number between `1` and `N-1`. In case, such a function does not exist in the used library, we should generate `k_bn` in a while loop by generating it as a set of 32 random bytes but checking at each iteration whether `k_bn` lies between `1` and `N-1`. Note that we should not attempt to do a modulo `N` here.    @nickcen @neeboo

**Comment by neeboo** [comment]
Thanks @AmritKumar, we will look into it

**Comment by nickcen** [comment]
@AmritKumar I have submit the fix, plz check it out. 530a81095456d41971e70286be2471b33899b0cb
